### ISSUE TITLE
how to output the parameter of accuracy and loss?

### ISSUE THREAD

**Issue by Billy1900** [metobom/prepare-data-for-UNet#1]
I want to output the accuracy and loss after I test the dataset, how could I do that?

**Comment by metobom** [comment]
Sorry I don't know that. I was looking for it too and I found  model.evaluate_generator() but I couldn't understand input of this function.

**Comment by Billy1900** [comment]
I guess the best way is to rewrite the whole thing nearly.

**Comment by metobom** [comment]
> I guess the best way is to rewrite the whole thing nearly.

I added confusion_mat.py. You can use it if you are doing a black/white binary classification. If you find an error, please let me know.

**Comment by metobom** [comment]
I added confusion_mat.py to get test accuracy. You can use it if you are doing a black/white binary classification. Please let me know if there are anything wrong with code.
