### ISSUE TITLE
i did not get "labelme" step?

### ISSUE THREAD

**Issue by manvirvirk** [metobom/prepare-data-for-UNet#2]
Please help?

**Comment by metobom** [comment]
Can you be more specific?

**Comment by manvirvirk** [comment]
Can you please explain the first step ? How to proceed?  

Tarundeep Singh Virk

**Comment by metobom** [comment]
1- Git clone labelme from here: https://github.com/wkentaro/labelme
2- Open labelme and click on Open Dir. Select your image's path.
3- Begin masking your images with polygons.
4- After you complete masking, there will be json files in next to your images.
5- Check here(https://github.com/wkentaro/labelme/tree/master/examples/tutorial#tutorial-single-image-example) and do whatever you need to do with json files.
6- If you use "labelme_json_to_dataset" output masks will be colored. But you need black and white images for UNet. To convert these colored masks to black and white use prepare_mask.py in my repo. (White color is you class, black is background)
You can write again if there are problems.

**Comment by manvirvirk** [comment]
thanks for helping

**Comment by manvirvirk** [comment]
In step no.2 i could not find Open Dir. Where is that??? Thanks

**Comment by metobom** [comment]
![image](https://user-images.githubusercontent.com/46991761/78499820-909a9300-775b-11ea-8d68-a4a093a5afe7.png)
Here

**Comment by manvirvirk** [comment]
i could not find this window tab

**Comment by metobom** [comment]
Do you use Windows?

**Comment by manvirvirk** [comment]
yes window 10

**Comment by metobom** [comment]
Open cmd or Powershell and type labelme do open labelme.

**Comment by manvirvirk** [comment]
ok

**Comment by manvirvirk** [comment]
it is showing "windows cannot find labelme.

**Comment by metobom** [comment]
Try to open cmd where you downloaded labelme.

**Comment by manvirvirk** [comment]
ok

**Comment by metobom** [comment]
> ok

Is everything fine?

**Comment by manvirvirk** [comment]
not yet. could not get it.

**Comment by manvirvirk** [comment]
yea git it. thanks for helping long way :)

**Comment by metobom** [comment]
You're welcome :D

**Comment by manvirvirk** [comment]
after selecting image , we have to click on "create polygon" tab, right? so now where images will be saved ??

**Comment by metobom** [comment]
From Open Dir choose your image's path click on create polygon, mask your image, save your image and go to next image. Related json files will be saved next to your images.

**Comment by manvirvirk** [comment]
my json file is not saved anywhere???

**Comment by manvirvirk** [comment]
![Capture](https://user-images.githubusercontent.com/54542400/78501237-7622e280-7778-11ea-9679-6fc46722691e.PNG)

**Comment by manvirvirk** [comment]
this is what i m getting

**Comment by manvirvirk** [comment]
again got it :)

**Comment by metobom** [comment]
I prepared a tutorial for you: https://www.youtube.com/watch?v=JJuFEqD0mZI&feature=youtu.be

**Comment by manvirvirk** [comment]
thanks:)

**Comment by manvirvirk** [comment]
this is what my json files look like. now after creating this what is the
next step???

**Comment by metobom** [comment]
Put your masks to data/train/label and images to data/train/image and train

**Comment by manvirvirk** [comment]
unet) D:\labelme-master\images>labelme_json_to_dataset epoch020_fake_A.json
-o epoch020_fake_A
'labelme_json_to_dataset' is not recognized as an internal or external
command,
operable program or batch file.

getting this error

**Comment by manvirvirk** [comment]
solved it . thanks

**Comment by manvirvirk** [comment]
able to create label

**Comment by manvirvirk** [comment]
i have put all images in data/train/images and masks in data/train/label in
original unet repo. Now i have run main.py file for segmentation ??

**Comment by metobom** [comment]
Please read repo
